version: '3.8'

services:
  db:
    image: postgres:13.1
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: russel07/usd_rate_bot_backend:latest
    container_name: web
    env_file:
      - ./.env
    restart: always
    volumes:
      - staticfiles:/code/backend_project/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/code/backend_project/static
    ports:
      - 80:80
    depends_on:
      - web

  telegram:
    image: russel07/usd_rate_bot_telegram:latest
    container_name: telegram
    env_file:
      - ./.env
    restart: always
    depends_on:
      - nginx

volumes:
  postgres_data:
  staticfiles:
