version: '3.8'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:13.1
    container_name: tg_bot_postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    image: russel07/foodgram:latest
    container_name: tg_bot_backend
    env_file:
      - ./.env
    restart: always
    volumes:
      - staticfiles:/code/foodgram_project/static
      - staticfiles:/code/foodgram_project/media
    depends_on:
      - db

  telegram:
    image: russel07/foodgram:latest
    container_name: tg_bot_telegram
    env_file:
      - ./.env
    restart: always
    depends_on:
      - web

  nginx:
    image: nginx:1.19.6
    container_name: tg_bot_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/code/foodgram_project/static
    ports:
      - 80:80
    depends_on:
      - telegram